version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - thread_pool.write.queue_size=1000
      - elasticsearch.requestTimeout=1000
    healthcheck:
      test: "curl localhost:9200/_cluster/health"
      interval: "10s"
      timeout: "1s"
      retries: 20
      start_period: "10s"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      CSP_STRICT: "false"
      SERVER_MAXPAYLOADBYTES: 104857600000000
    ports:
       - 5601:5601
